name: Bug Report
description: Report broken or unexpected behavior
labels: [bug, triage]
body:
  - type: markdown
    attributes:
      value: |
        If troubleshooting does not reveal any useful information, please fill out the bug report below.

        Thank you for taking the time to report this!
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: Tell us what you expected to happen.
      placeholder: Tell us what you expected to happen.
      value: "I expected this,"
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: Tell us what you see!
      placeholder: Tell us what you see!
      value: "But a bug happened like this,"
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: |
        Copy and paste any relevant log output here (most issues will be difficult to diagnose without this). 
        For best results please make sure that debug logging is enabled (`esbonio.logging.level = debug`)
        This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: textarea
    id: conf
    attributes:
      label: (Optional) Settings from conf.py
      description: |
        If you think any settings from your project's conf.py are applicable, feel free to include them here
        This will be automatically formatted into code, so no need for backticks.
      render: python
