name: Feature Request
description: Suggest an idea for this project
labels: [enhancement, triage]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill this out!
  - type: textarea
    id: solution
    attributes:
      label: What would you like to see
      description: A clear and concise description of what you want to happen.
      placeholder: A clear and concise description of what you want to happen.
    validations:
      required: true
